---
 - hosts: all
   sudo: yes
   tasks:
     - name: Upgrade all packages in RedHat-based machines
       when: ansible_os_family == "Redhat"
       yum: name=* state=latest

     - name: Upgrade all packages in Debian-based machines
       when: ansible_os_family == "Debian"
       apt: upgrade=dist update_cache=yes

     - name: Reboot server
       command: /sbin/reboot
       ignore_errors: true

     - name: Wait for the server to finish rebooting
       sudo: no
       local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
